server_mac: "20:25:64:84:cf:96"
server_ip: "192.168.1.140"
server_mask: 24
proxy_port: 11434
proxy_dial_timeout: 30 * time.Second
proxy_xfer_timeout: 5 * time.Second

ping_log_status_change: true

wol_port: 9
wol_detect_interval: 10sec
wol_retry_interval: 500ms
wol_max_retries: 3

max_idle_connections: 100
shutdown_timeout: 1sec

log_maxsize: 1
log_maxbackups: 4
log_rotateat: []
log_level: "info"
log_file: "./wol-proxy.log"
